### ISSUE TITLE
broken dependencies (basesystem, ttmkfdir)

### ISSUE THREAD

**Issue by lkocman** [fedora-modularity/whatpkgs#3]
So far I triggered few builds and you guys are missing these

basesystem
ttmkfdir
## 

DEBUG util.py:421:  Error: Package: glibc-2.24-3.fc25.x86_64 (build)
DEBUG util.py:421:             Requires: basesystem

Error: Package: xorg-x11-fonts-Type1-7.5-16.fc24.noarch (build)
           Requires: ttmkfdir

I just imported basesystem-11-2.fc24, ttmkfdir-3.0.9-48.fc24

**Comment by lkocman** [comment]
I bet there will be more missing, do you want to find your repoclosure bug and do new depsolving?

**Comment by lkocman** [comment]
$ ./koji-bootstrap.py --builds-from-file missing.txt --workdir /root/import-brew-stage --koji-dest-profile koji-stage --import-owner lkocman --import-dest-tag base-runtime-0.25-1 --koji-profile koji --import-builds  
INFO:koji-bootstrap:Downloading basesystem-11-2.fc24 (1/2)
INFO:koji-bootstrap:Downloading nvr basesystem-11-2.fc24 from koji-profile koji
INFO:koji-bootstrap:Downloading ttmkfdir-3.0.9-48.fc24 (2/2)
INFO:koji-bootstrap:Downloading nvr ttmkfdir-3.0.9-48.fc24 from koji-profile koji

**Comment by sgallagher** [comment]
Yeah, we're aware of that issue. It was due to a difference between DNF's display of `Requires:` vs. `Requires(pre):` compared to how yum's repoquery code worked. It's been fixed and I'll have new content up later today or tomorrow.

**Comment by sgallagher** [comment]
@lkocman Please try from the package lists at https://github.com/sgallagher/whatpkgs/tree/d62163cfa785169c5e1e741f044b72afc6d368f3/sampledata

which should have all the correct dependencies this time.

**Comment by sgallagher** [comment]
This has been fixed for a while.
