### ISSUE TITLE
Missing fedpkg-minimal

### ISSUE THREAD

**Issue by ralphbean** [fedora-modularity/whatpkgs#5]
This is needed for building srpms.

Does it belong in the sampledata?

**Comment by sgallagher** [comment]
Sorry, I don't understand the question. Could you elaborate?

**Comment by ralphbean** [comment]
Yeah, `fedpkg-minimal` is needed by the `srpm-build` group in koji when doing a `buildSRPMfromSCM` task.

Since we were using the `koji-bootstrap` script here to initialize a fake base-runtime tag there, I thought that we should (maybe) add `fedpkg-minimal` to some of the sampledata.  Does that help?

**Comment by sgallagher** [comment]
Hmm, that may be necessary for the self-hosting list, yes. I'll discuss it with Petr today.

**Comment by contyk** [comment]
I've been thinking about this and I don't have a definite answer to the problem yet.

The original idea was to have special modules that would define the common buildroot and srpm-buildroot for everyone. I also thought, following some old conversation with Lubos, that these groups would be temporarily pre-defined, using F25 packages, before we get to creating proper modules for them.

I no longer think this would be the optimal way forward, however. Far from it. For now, let's assume that buildroot = srpm-buildroot = module build dependencies. For that to work we'll have to add all the content from today's f25 buildroot and srpm-buildroot groups to our prototype. I'll create another issue for that.

**Comment by sgallagher** [comment]
I'm pretty sure this is addressed in the modularity build infrastructure now.
